version: "3.8"

services:
  student-management:
    image: student-management:latest
    container_name: student-management
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
